// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/AlmazDefourten/goapp/container"
	"github.com/AlmazDefourten/goapp/models"
	"github.com/AlmazDefourten/goapp/services"
)

// Injectors from wire.go:

// Initialize container with global app dependencies -
// Connection, configurator, etc...
func InitializeContainer() models.Container {
	viper := container.NewViperConfigurator()
	db := container.NewConnection(viper)
	modelsContainer := container.NewContainer(db, viper)
	return modelsContainer
}

// Initialize services examples
func InitializeServiceContainer(container_init *models.Container) models.Services {
	userService := services.NewUserService(container_init)
	modelsServices := container.NewServices(userService)
	return modelsServices
}
