// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/AlmazDefourten/goapp/container"
)

// Injectors from wire.go:

func InitializeContainer() container.Container {
	viper := container.NewViperConfigurator()
	db := container.NewConnection(viper)
	containerContainer := container.NewContainer(db, viper)
	return containerContainer
}
