// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/AlmazDefourten/goapp/infrastructure/configurator"
	"github.com/AlmazDefourten/goapp/infrastructure/data_adapter/connection"
	"github.com/AlmazDefourten/goapp/interface/handler"
	"github.com/AlmazDefourten/goapp/models"
	"github.com/AlmazDefourten/goapp/models/container_models"
	"github.com/AlmazDefourten/goapp/pkg/logging/loggers"
	"github.com/AlmazDefourten/goapp/pkg/logging/resolvers"
	"github.com/AlmazDefourten/goapp/services"
)

// Injectors from wire.go:

// Initialize container with global app dependencies -
// Connection, configurator, etc...
func InitializeContainer(typeLogger resolvers.TypeLogger) container_models.Container {
	viper := configurator.NewViperConfigurator()
	db := connection.NewGormConnection(viper)
	container := NewContainer(db, viper)
	return container
}

// Initialize dependencies for services
func InitServiceDependency(container_inited *container_models.Container) container_models.ServiceContainer {
	userService := services.NewUserService(container_inited)
	jwtService := services.NewJWTService(container_inited)
	authService := services.NewAuthService(container_inited, jwtService)
	serviceContainer := NewServiceContainer(userService, jwtService, authService)
	return serviceContainer
}

// Initialize dependencies for handlers
func InitHandlerDependency(userService models.IUserService, authService models.IAuthService) container_models.HandlerContainer {
	userInfoHandler := handler.NewUserInfoHandler(userService)
	authHandler := handler.NewAuthHandler(authService)
	handlerContainer := NewHandlerContainer(userInfoHandler, authHandler)
	return handlerContainer
}

func InitLogrusLogger(typeLogger resolvers.TypeLogger) models.Logger {
	entry := loggers.Init(typeLogger)
	return entry
}

// wire.go:

// RegisterServices - decomposition ServiceContainer to services
func RegisterServices(serviceContainer container_models.ServiceContainer) container_models.HandlerContainer {
	return InitHandlerDependency(
		serviceContainer.UserService,
		serviceContainer.AuthService,
	)
}
