// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/AlmazDefourten/goapp/interface/handler"
	"github.com/AlmazDefourten/goapp/models"
	"github.com/AlmazDefourten/goapp/services"
)

// Injectors from wire.go:

// Initialize container with global app dependencies -
// Connection, configurator, etc...
func InitializeContainer() models.Container {
	viper := NewViperConfigurator()
	db := NewConnection(viper)
	container := NewContainer(db, viper)
	return container
}

// Initialize dependencies for services
func InitServiceDependency(container_inited *models.Container) models.ServiceContainer {
	userService := services.NewUserService(container_inited)
	serviceContainer := NewServiceContainer(userService)
	return serviceContainer
}

// Initialize dependencies for handlers
func InitHandlerDependency(userService models.IUserService) HandlerContainer {
	userInfoHandler := handler.NewUserInfoHandler(userService)
	handlerContainer := NewHandlerContainer(userInfoHandler)
	return handlerContainer
}

// wire.go:

// RegisterServices - decomposition ServiceContainer to services
func RegisterServices(serviceContainer *models.ServiceContainer) HandlerContainer {
	return InitHandlerDependency(
		serviceContainer.UserService,
	)
}
