name: GitHub Action

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install PPTP client
        run: sudo add-apt-repository ppa:nm-l2tp/network-manager-l2tp && sudo apt-get install -y network-manager-l2tp && sudo apt-get install -y network-manager-l2tp-gnome && sudo apt-get install -y strongswan && sudo apt-get install -y xl2tpd && sudo apt-get install expect
      - name: Create VPN config file
        run: |
          sudo curl -o VPN-KAI.conf https://raw.githubusercontent.com/AlmazDefourten/pears/dev/.github/workflows/VPN-KAI.conf
          sudo mv VPN-KAI.conf /etc/NetworkManager/system-connections/
          sudo chmod 600 /etc/NetworkManager/system-connections/VPN-KAI.conf
          cd /etc/netplan/
          sudo sed -i 's/managed=false/managed=true/g' /etc/NetworkManager/NetworkManager.conf
          sudo sed -i 's/version: 2/version: 2\n    renderer: NetworkManager/g' 50-cloud-init.yaml
          sudo netplan apply
          sudo systemctl restart NetworkManager
          sudo cat 50-cloud-init.yaml
          sudo nmcli connection import type l2tp file /etc/NetworkManager/system-connections/VPN-KAI.conf
          ip route
          except "Password (vpn.secrets.password):"
          send "ivcgid72\r"
          except "Pre-shared key (PSK) (vpn.secrets.ipsec-psk):"
          send "KAI-ALL-KEY\r"
          sudo nmcli connection up VPN-KAI --ask
          sudo ip route add 10.0.0.59/32 via 0.0.0.0 dev ppp0
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for VPN plugin errors
        if: ${{ failure() }}
        run: 
          sudo journalctl --since "5 minutes ago" --no-pager -u NetworkManager.service
      - name: Use SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export GOROOT=/home/u_studpr/goinst/go
            export GOPATH=$HOME/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH    
            source ~/.bashrc
            screen -ls | grep -o '[0-9]\+\.' | sed 's/.$//' | xargs -I % sh -c 'screen -S % -X quit'
            cd app/pears/api
            git pull
            go build
            screen -dmS myapp go run .


