name: GitHub Action

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install PPTP client
        run: sudo add-apt-repository ppa:nm-l2tp/network-manager-l2tp && sudo apt install network-manager-l2tp
      - name: Create VPN config file
        run: |
          sudo nmcli connection add type vpn vpn-type l2tp con-name "kai" ifname "*" vpn.data "gateway=vpn1.kai.ru,ipsec-psk=KAI-ALL-KEY,user=SakhabievAI@stud.kai.ru,password=ivcgid72,refuse-chap=yes,refuse-mschap=yes,refuse-eap=yes,require-pap=yes,l2tp-require-chap=no,l2tp-require-mschap=no,l2tp-require-mschapv2=no,l2tp-use-ipsec=yes,ipsec-esp=aes128-sha1-modp1024!,ipsec-ike=aes128-sha1!,no-compression=yes
      - name: Connect to VPN
        run: |
          nmcli connection show kai
          nmcli c up kai
          sudo ip route add 10.0.0.59/32 via 0.0.0.0 dev ppp0
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export GOROOT=/home/u_studpr/goinst/go
            export GOPATH=$HOME/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH    
            source ~/.bashrc
            screen -ls | grep -o '[0-9]\+\.' | sed 's/.$//' | xargs -I % sh -c 'screen -S % -X quit'
            cd app/pears/api
            git pull
            go build
            screen -dmS myapp go run .


