name: GitHub Action

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install pptp-linux
        run: sudo apt-get update && sudo apt-get install -y pptp-linux
      - name: Create PPTP configuration
        run: |
          echo "pty \"pptp vpn.kai.ru --nolaunchpppd\"" | sudo tee /etc/ppp/peers/pptp-vpn > /dev/null
          echo "name u_studpr" | sudo tee -a /etc/ppp/peers/pptp-vpn > /dev/null
          echo "password zudXX}zT?Kj" | sudo tee -a /etc/ppp/peers/pptp-vpn > /dev/null
          echo "refuse-pap" | sudo tee -a /etc/ppp/peers/pptp-vpn > /dev/null
          echo "refuse-eap" | sudo tee -a /etc/ppp/peers/pptp-vpn > /dev/null
          echo "refuse-chap" | sudo tee -a /etc/ppp/peers/pptp-vpn > /dev/null
          echo "refuse-mschap" | sudo tee -a /etc/ppp/peers/pptp-vpn > /dev/null
          echo "require-mschap-v2" | sudo tee -a /etc/ppp/peers/pptp-vpn > /dev/null
          echo "require-mppe-128" | sudo tee -a /etc/ppp/peers/pptp-vpn > /dev/null
          echo "mppe-stateful" | sudo tee -a /etc/ppp/peers/pptp-vpn > /dev/null
          echo "noipdefault" | sudo tee -a /etc/ppp/peers/pptp-vpn > /dev/null
          echo "defaultroute" | sudo tee -a /etc/ppp/peers/pptp-vpn > /dev/null
      - name: Start PPTP connection
        run: sudo pon pptp-vpn
      - name: Check connection status
        run: |
          while ! ping -c 1 google.com; do sleep 1; done
          echo "Connected to VPN"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          timeout: 200s
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export GOROOT=/home/u_studpr/goinst/go
            export GOPATH=$HOME/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH    
            source ~/.bashrc
            screen -ls | grep -o '[0-9]\+\.' | sed 's/.$//' | xargs -I % sh -c 'screen -S % -X quit'
            cd app/pears/api
            git pull
            go build
            screen -dmS myapp go run .
      - name: Stop PPTP connection
        run: sudo poff pptp-vpn

