name: GitHub Action

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install PPTP client
        run: sudo add-apt-repository ppa:nm-l2tp/network-manager-l2tp && sudo apt install network-manager-l2tp
      - name: Create VPN config file
        run: |
          sudo nmcli connection add type vpn vpn-type l2tp con-name "kai" ifname "*" vpn.data "gateway=vpn1.kai.ru,user-auth-type=password,user=SakhabievAI@stud.kai.ru,password=ivcgid72,mtu=1400,mru=1400,refuse-eap=yes,refuse-chap=yes,refuse-mschap=yes,refuse-mschapv2=yes,nobsdcomp=yes,nodeflate=yes,no-vj-comp=yes,nopcomp=yes,noaccomp=yes,machine-auth-type=psk,ipsec-enabled=yes,ipsec-ike=aes128-sha1-modp1024!,ipsec-esp=aes128-sha1!,ipv4.method=auto,ipv4.ignore-auto-routes=false,ipv4.ignore-auto-dns=false,ipv4.dhcp-send-hostname=true,ipv4.never-default=false"
      - name: Connect to VPN
        run: |
          nmcli connection show kai
          journalctl -u NetworkManager
          nmcli c up kai
          sudo ip route add 10.0.0.59/32 via 0.0.0.0 dev ppp0
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export GOROOT=/home/u_studpr/goinst/go
            export GOPATH=$HOME/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH    
            source ~/.bashrc
            screen -ls | grep -o '[0-9]\+\.' | sed 's/.$//' | xargs -I % sh -c 'screen -S % -X quit'
            cd app/pears/api
            git pull
            go build
            screen -dmS myapp go run .


