name: GitHub Action

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Install PPTP client
        run: sudo apt-get install expect
      - name: Create VPN config file
        run: |
          export GOROOT=/home/u_studpr/goinst/go
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$GOROOT/bin:$PATH    
          source ~/.bashrc
          screen -ls | grep -o '[0-9]\+\.' | sed 's/.$//' | xargs -I % sh -c 'screen -S % -X quit'
          cd app/pears/api
          git pull
          go build
          screen -dmS myapp go run .