name: GitHub Action

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install PPTP client
        run: sudo apt-get update && sudo apt-get install -y pptp-linux
      - name: Create VPN config file
        run: |
          echo 'pty "pptp ${{ secrets.VPN_SERVER }} --nolaunchpppd"' | sudo tee /etc/ppp/peers/kai-vpn > /dev/null
          echo 'name ${{ secrets.VPN_USERNAME }}' | sudo tee -a /etc/ppp/peers/kai-vpn > /dev/null
          echo 'password ${{ secrets.VPN_PASSWORD }}' | sudo tee -a /etc/ppp/peers/kai-vpn > /dev/null
          echo 'remotename kai-vpn' | sudo tee -a /etc/ppp/peers/kai-vpn > /dev/null
          echo 'refuse-eap' | sudo tee -a /etc/ppp/peers/kai-vpn > /dev/null
          echo 'refuse-pap' | sudo tee -a /etc/ppp/peers/kai-vpn > /dev/null
          echo 'refuse-chap' | sudo tee -a /etc/ppp/peers/kai-vpn > /dev/null
          echo 'refuse-mschap' | sudo tee -a /etc/ppp/peers/kai-vpn > /dev/null
          echo 'require-mschap-v2' | sudo tee -a /etc/ppp/peers/kai-vpn > /dev/null
          echo 'noauth' | sudo tee -a /etc/ppp/peers/kai-vpn > /dev/null
          echo 'debug' | sudo tee -a /etc/ppp/peers/kai-vpn > /dev/null
          echo 'maxfail 10' | sudo tee -a /etc/ppp/peers/kai-vpn > /dev/null
          echo 'nodefaultroute' | sudo tee -a /etc/ppp/peers/kai-vpn > /dev/null
      - name: Connect to VPN
        run: |
          sudo pppd call kai-vpn
          ping -w 30 -c 1 10.0.0.59 || true
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export GOROOT=/home/u_studpr/goinst/go
            export GOPATH=$HOME/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH    
            source ~/.bashrc
            screen -ls | grep -o '[0-9]\+\.' | sed 's/.$//' | xargs -I % sh -c 'screen -S % -X quit'
            cd app/pears/api
            git pull
            go build
            screen -dmS myapp go run .


