name: GitHub Action

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install PPTP client
        run: sudo add-apt-repository ppa:nm-l2tp/network-manager-l2tp && sudo apt install network-manager-l2tp
      - name: Create VPN config file
        run: |
          sudo nmcli connection add connection.id kai con-name kai type VPN vpn-type l2tp ifname -- connection.autoconnect no ipv4.method auto vpn.data "gateway = vpn1.kai.ru, ipsec-enabled = yes, mru = 1400, mtu = 1400, password flags = 0, refuse-chap = yes, refuse-mschap = yes, refuse-pap = no, require-mppe = yes, user = SakhabievAI" vpn.secrets "password=ivcgid72, ipsec-psk = KAI-ALL-KEY"
      - name: Connect to VPN
        run: |
          nmcli c up kai
          ping -w 30 -c 1 10.0.0.59 || true
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export GOROOT=/home/u_studpr/goinst/go
            export GOPATH=$HOME/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH    
            source ~/.bashrc
            screen -ls | grep -o '[0-9]\+\.' | sed 's/.$//' | xargs -I % sh -c 'screen -S % -X quit'
            cd app/pears/api
            git pull
            go build
            screen -dmS myapp go run .


