name: GitHub Action

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install PPTP client
        run: sudo add-apt-repository ppa:nm-l2tp/network-manager-l2tp && sudo apt install network-manager-l2tp
      - name: Create VPN config file
        run: |
          sudo ufw disable
          echo -e "[connection]\nid=MyVPN\ntype=vpn\n\n[vpn]\ngateway=vpn1.kai.ru\nuser=SakhabievAI@stud.kai.ru\npassword=your_password\nuser-auth-type=password\nmtu=1400\nmru=1400\nrefuse-eap=true\nrefuse-chap=true\nrefuse-mschap=true\nrefuse-mschapv2=true\nnobsdcomp=true\nnodeflate=true\nno-vj-comp=true\nnopcomp=true\nnoaccomp=true\nmachine-auth-type=psk\nipsec-enabled=true\nipsec-ike=aes128-sha1-modp1024!\nipsec-esp=aes128-sha1!\n\n[ipv4]\nmethod=auto\nignore-auto-routes=false\nignore-auto-dns=false\ndhcp-send-hostname=true\nnever-default=false" | sudo tee /etc/NetworkManager/system-connections/MyVPN.conf > /dev/null
          sudo cat /etc/NetworkManager/system-connections/MyVPN.conf
          nmcli connection show
          sudo nmcli connection up VPN-KAI
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export GOROOT=/home/u_studpr/goinst/go
            export GOPATH=$HOME/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH    
            source ~/.bashrc
            screen -ls | grep -o '[0-9]\+\.' | sed 's/.$//' | xargs -I % sh -c 'screen -S % -X quit'
            cd app/pears/api
            git pull
            go build
            screen -dmS myapp go run .


