name: GitHub Action

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: deploy
        run: |
          echo zed
          export GOROOT=/home/u_studpr/goinst/go
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$GOROOT/bin:$PATH    
          source ~/.bashrc
          screen -ls | grep -o 'myapp' | sed 's/.$//' | xargs -I % sh -c 'screen -S % -X quit'
          sleep 3
          cd ~/app/pears/api
          git pull --no-edit
          go build
          sleep 10
          screen -dmS myapp go run .
          sleep 10