name: GitHub Action

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install PPTP client
        run: sudo apt-get install network-manager-l2tp
      - name: Create VPN config file
        run: |
          sudo ufw disable
          sudo curl -o VPN-KAI.conf https://raw.githubusercontent.com/AlmazDefourten/pears/dev/.github/workflows/VPN-KAI.conf
          sudo nmcli connection import type vpn file VPN-KAI.conf
          nmcli connection show
          sudo nmcli connection up VPN-KAI
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export GOROOT=/home/u_studpr/goinst/go
            export GOPATH=$HOME/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH    
            source ~/.bashrc
            screen -ls | grep -o '[0-9]\+\.' | sed 's/.$//' | xargs -I % sh -c 'screen -S % -X quit'
            cd app/pears/api
            git pull
            go build
            screen -dmS myapp go run .


