name: Connect to PPTP VPN

on: [push]

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: Install VPN dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pptp-linux
      
      - name: Configure VPN connection
        run: |
          sudo cat > /etc/ppp/peers/vpn <<EOF
          pty "pptp ${{ secrets.VPN_SERVER }} --nolaunchpppd"
          name ${{ secrets.VPN_USERNAME }}
          require-mppe-128
          refuse-pap
          refuse-chap
          refuse-mschap
          require-mschap-v2
          refuse-eap
          nwid "10.0.0.0/24"
          EOF
          
      - name: Connect to VPN
        run: | 
          echo "${{ secrets.VPN_PASSWORD }}" | sudo pppd call vpn
          
      - name: Check VPN connection status
        run: |
          sudo ip r
