name: GitHub Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Connect to PPTP VPN
          uses: mizumotok/pptp-action@v1
          with:
            server: ${{ secrets.VPN_SERVER }}
            username: ${{ secrets.VPN_USERNAME }}
            password: ${{ secrets.VPN_PASSWORD }}
      - name: Use SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export GOROOT=/home/u_studpr/goinst/go
            export GOPATH=$HOME/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH    
            source ~/.bashrc
            screen -ls | grep -o '[0-9]\+\.' | sed 's/.$//' | xargs -I % sh -c 'screen -S % -X quit'
            cd app/pears/api
            git pull
            go build
            screen -dmS myapp go run .

